# Generated by Django 3.2.7 on 2021-12-06 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_good', models.CharField(max_length=20, verbose_name='Товар')),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='app.catalogs')),
            ],
            options={
                'verbose_name': 'Good',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_good', models.IntegerField(default=0)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.basket')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Goods_descr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=40)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_descr', to='app.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_good', models.IntegerField(default=0)),
                ('good_price', models.IntegerField(default=0)),
                ('good_full_price', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('S', 'InStock'), ('O', 'OnBuying'), ('T', 'TimeIsOut'), ('B', 'Bought'), ('C', 'Canceled')], default='S', help_text='Purchasing status', max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought', to='app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='app.profile'),
        ),
    ]
