# Generated by Django 3.2.7 on 2021-12-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought',
            name='good_name',
            field=models.CharField(blank=True, default='None', max_length=30, null=True),
        ),
    ]
