# Generated by Django 3.2.7 on 2021-12-06 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bought_good_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bought',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'InStock'), ('O', 'OnBuying'), ('T', 'TimeIsOut'), ('B', 'Bought'), ('C', 'Canceled')], default='S', help_text='Purchasing status', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.basket'),
        ),
    ]
