# Generated by Django 3.2.7 on 2021-12-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211206_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bought',
            name='good_full_price',
        ),
        migrations.RemoveField(
            model_name='bought',
            name='good_name',
        ),
        migrations.RemoveField(
            model_name='bought',
            name='good_price',
        ),
        migrations.RemoveField(
            model_name='bought',
            name='num_of_good',
        ),
    ]
