# Generated by Django 3.2.7 on 2021-12-06 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211206_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bought',
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app.profile'),
        ),
    ]
