# Generated by Django 3.2.7 on 2021-12-06 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought', to='app.profile'),
        ),
    ]
