# Generated by Django 3.2.7 on 2021-12-06 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211206_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profile',
        ),
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bg', to='app.bought'),
        ),
    ]
