# Generated by Django 3.2.7 on 2021-12-06 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_full_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bought',
            name='data',
        ),
        migrations.AddField(
            model_name='product',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
