# Generated by Django 3.2.7 on 2021-12-06 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211206_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 6, 59, 22, 877644)),
        ),
    ]
