# Generated by Django 3.2.7 on 2021-12-06 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_product_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 7, 11, 40, 546744)),
        ),
    ]
