# Generated by Django 3.2.7 on 2021-12-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
