# Generated by Django 3.2.7 on 2021-12-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_product_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='full_price',
        ),
        migrations.AddField(
            model_name='product',
            name='good_full_price',
            field=models.IntegerField(default=0),
        ),
    ]
